### ISSUE TITLE
UnsupportedBackendScheme: scheme not supported in url

### ISSUE THREAD

**Issue by matthewjewell** [matthewbentley/duplicity_b2#1]
Hi, 

Using duplicity 0.6.26, installed via homebrew. Encountering the above error when using a b2:// scheme. 

My backends folder is found at `/usr/local/Cellar/duplicity/0.6.26_1/libexec/lib/python2.7/site-packages/duplicity/backends`

Have I missed a step?

**Comment by mtbentley** [comment]
I haven't tested with 0.6.26.  This plugin should work with duplicity 0.7+

I will look into what it will take to backport to 0.6.26.

**Comment by matthewjewell** [comment]
Ah, I did wonder if this might be the case (something to add to readme?). Time for an upgrade anyway, will give it a go and report back.

**Comment by mtbentley** [comment]
After a bit of testing, it looks like I won't be able to backport this with a reasonable amount of work.

**Comment by matthewjewell** [comment]
Up and running fine with 0.7, thanks!
