### ISSUE TITLE
UnsupportedBackendScheme: scheme not supported in url

### ISSUE THREAD

**Issue by adrianmihalko** [matthewbentley/duplicity_b2#2]
Hi Matthew,

On Ubuntu the backend location is:

/usr/lib/python2.7/dist-packages/duplicity/backends/

I installed the backend here, but I still get error, when I am trying to run:

duplicity importers/ b2://123a1456a23233a@my_bucket_name/

Import of duplicity.backends.b2backend Failed: cannot import name FatalBackendException

**Comment by mtbentley** [comment]
Which version of Ubuntu and Duplicity are you using? This seems to only be compatible with duplicity 0.7+, which comes with Ubuntu 15.04+.

I don't plan on supporting old versions of Duplicity, but work to do so is happening here: https://github.com/sondree/duplicity_b2

**Comment by adrianmihalko** [comment]
Super, this was the problem, I have duplicity 0.6.23.

Edit:

In the meantime I upgraded to the latest 0.7.05, and there is another problem:

^Cmadrian@ubuntu:~$ FTP_PASSWORD=xy duplicity Dropbox/BackupUbuntu/scripts/ b2://id@bucketname/123/
Synchronizing remote metadata to local cache...
GnuPG passphrase: 
Copying duplicity-full-signatures.20151204T231414Z.sigtar.gpg to local cache.
Attempt 1 failed. HTTPError: HTTP Error 404: Not Found
Attempt 2 failed. HTTPError: HTTP Error 404: Not Found
@ubuntu:~$ FTP_PASSWORD=xy duplicity  list-current-files b2://id@bucketname/123/
Synchronizing remote metadata to local cache...
GnuPG passphrase: 
Copying duplicity-full-signatures.20151204T231414Z.sigtar.gpg to local cache.
Attempt 1 failed. HTTPError: HTTP Error 404: Not Found

It works for one directory only @bucketname/scripts/ (upload, list) which I created first, but I have another directory for test @bucketname/123/ or root @bucketname/  - 404 error.

**Comment by mtbentley** [comment]
Can you add `print(self.path, filename)` after line 316 in b2backend.py and re-run the command?

**Comment by adrianmihalko** [comment]
Hmm, I added, but now I get UnsupportedBackendScheme error.

<img width="722" alt="screen-shot-2015-12-05-13-11-29" src="https://cloud.githubusercontent.com/assets/733361/11607703/d8a5c13c-9b51-11e5-8510-897cfe301a9b.png">

**Comment by adrianmihalko** [comment]
I thought that this is a caching issue only, but it's not, I cleared the: .cache/duplicity/ directory, but the problem is the same:
![adrianmihalko_ _madrian_ubuntu____ _ssh_madrian_otthon_mihalko_eu_ _115x38_and_0_of_1_uploaded_-_youtube](https://cloud.githubusercontent.com/assets/733361/11608570/37f86692-9b6d-11e5-874c-8e97f8443303.jpg)

**Comment by adrianmihalko** [comment]
More info + log:

https://bugs.launchpad.net/duplicity/+bug/1523498

**Comment by knabar** [comment]
@adrianmihalko Are you trying to store multiple backups in the some bucket?  I got 404 errors when trying that, this PR should fix it: https://github.com/matthewbentley/duplicity_b2/pull/4

**Comment by adrianmihalko** [comment]
Yes, super, the problem is now fixed.

One bug left: I can't list stored backup files on the server:

https://bugs.launchpad.net/duplicity/+bug/1523498/comments/10

The problem is related to this bug?

**Comment by mtbentley** [comment]
I'm not seeing any 404 errors with list-current-files.  Can you re-install from the launchpad source and try again?  I can provide brief instructions for doing so if needed.

**Comment by knabar** [comment]
@adrianmihalko I am also not seeing any 404 errors, `list-current-files` is working properly for me using B2.

**Comment by adrianmihalko** [comment]
:( I made a new installation on a new machine (=this is the third machine).

Here is the full process:

[duplicity.log.3.txt](https://github.com/matthewbentley/duplicity_b2/files/57136/duplicity.log.3.txt)

Really, what I am doing wrong? Isn't there any way to debug this?

**Comment by mtbentley** [comment]
I added some logging to the b2backend.py file on the master branch of this repo.  Can you replace your current b2backend.py file with this one and re-run with -v9?

**Comment by adrianmihalko** [comment]
Sure, here it is:

[new_log.txt](https://github.com/matthewbentley/duplicity_b2/files/57180/new_log.txt)

I just found this:
Copying duplicity-full-signatures.20151207T205519Z.sigtar.gpg to local cache.

From where the 20151207T205519Z.sigtar.gpg is coming from?

In the bucket I have:
duplicity-full-signatures.20151207T190609Z.sigtar.gpg

Maybe this is why I am getting 404 error?

**Comment by mtbentley** [comment]
That's probably the problem.  I'm not sure why duplicity is trying to get that file.  Have you tried deleting the cache (~/.cache/duplicity)?

**Comment by adrianmihalko** [comment]
Caches cleared:

madrian@ubuntu:~$ rm ~/.cache/duplicity/ -rf
madrian@ubuntu:~$ rm /tmp/tmp*

[new_log_2.txt](https://github.com/matthewbentley/duplicity_b2/files/57220/new_log_2.txt)

If you check line 57: here is requested the good file duplicity-full-signatures.20151207T190609Z.sigtar.gpg

If you look little bit down at line 67 you can see the bad file again.

What happens here? I really don't know.

**Comment by mtbentley** [comment]
Maybe you have a bad manifest file in B2? That could have happened if you are trying to upload to the same bucket/folder.  Have you tried uploading to a new bucket?

**Comment by adrianmihalko** [comment]
Maybe yes, If I remember good I tried to make backup in the same bucket, before @knabar's bugfix.

Uh, I need to create the backup again. :(

**Comment by knabar** [comment]
@adrianmihalko I think I know what the issue is - if you try to run a backup into the top folder when there is a backup in a folder, or into a folder that has the same prefix as another backup, the `_list()` method still returns too many file names. I'll open a PR with a fix.

**Comment by adrianmihalko** [comment]
Super, thank you. In the meantime I deleted the bucket and I am creating a new one. At this time I upload it to newbucket/subfolder.

**Comment by knabar** [comment]
@adrianmihalko check out https://github.com/matthewbentley/duplicity_b2/pull/5

**Comment by adrianmihalko** [comment]
Something else at this time:

"Attempt 1 failed. SSLError: The read operation timed out"

There are other people too who had this problem:
https://bugs.launchpad.net/duplicity/+bug/629136

I am trying to re-run the duplicity.

**Comment by mtbentley** [comment]
I get that error occasionally, but duplicity usually keeps going.  It's probably mostly because B2 is still in beta and requests occasionally fail.

**Comment by adrianmihalko** [comment]
It seems OK now... :)
